using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

namespace KirosEngine
{
    /// <summary>
    /// Writes errors generated by the engine to a log file
    /// </summary>
    class ErrorLogger
    {
        private static ErrorLogger _instance;
        private static string _filePath;
        private static string _directory;

        private ErrorLogger() { }

        /// <summary>
        /// Public accessor for the logger's instance
        /// </summary>
        public static ErrorLogger Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new ErrorLogger();
                }
                return _instance;
            }
        }

        /// <summary>
        /// The file path the logger writes to
        /// </summary>
        public string FilePath
        {
            get
            {
                return _filePath;
            }
            set
            {
                _directory = value;
                _filePath = string.Format(@"{0}/err_{1:dd_MM_yy_hh_mm}.log", value, DateTime.Now);
            }
        }

        /// <summary>
        /// Initialize the logger with the given file path
        /// </summary>
        /// <param name="filePath">The location to write the error logs to</param>
        public static void Initialize(string filePath)
        {
            ErrorLogger._directory = filePath;
            ErrorLogger._filePath = string.Format(@"{0}/err_{1:dd_MM_yy_hh_mm}.log", filePath, DateTime.Now);
        }

        /// <summary>
        /// Open and write the given text to the error log
        /// </summary>
        /// <param name="text">The text to write to the log</param>
        public static void Write(string text)
        {
            if (!Directory.Exists(_directory))
            {
                try
                {
                    Directory.CreateDirectory(_directory);
                }
                catch(IOException ex)
                {
                    Console.WriteLine(ex.Message);
                    Console.WriteLine(String.Format("Failed to create the log directory at: {0}", _directory));
                }
            }
            //appends the text in a format of "Time: text"
            File.AppendAllText(_filePath, string.Format("{0:HH:mm:ss}: {1}", DateTime.Now, text));
        }
    }
}
